parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $adminEmailAddress: '%env(MAIL_ADMIN)%'
            $spotifyCode: '%env(SPOTIFY_CODE)%'
            $environment: '%kernel.environment%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/Spotify/Entity/'
            - '../src/Kernel.php'

    # Argument Resolvers for automatic parameter binding
    App\Infrastructure\ArgumentResolver\DateTimeImmutableValueResolver:
        tags: ['controller.argument_value_resolver']

    App\Infrastructure\ArgumentResolver\SpotifyIdValueResolver:
        tags: ['controller.argument_value_resolver']

    App\Infrastructure\ArgumentResolver\SpotifyIdArrayValueResolver:
        tags: ['controller.argument_value_resolver']

    Symfony\Component\Cache\Adapter\AdapterInterface:
        class: Symfony\Component\Cache\Adapter\DoctrineDbalAdapter

    # Configure the serializer with proper normalizers
    serializer.normalizer.object:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        arguments:
            $classMetadataFactory: ~
            $nameConverter: ~
            $propertyAccessor: ~
            $propertyTypeExtractor: ~
            $classDiscriminatorResolver: ~
            $objectClassResolver: ~
            $defaultContext: []
        tags: ['serializer.normalizer']

    # Use the Symfony serializer service for both normalizer and denormalizer interfaces
    Symfony\Component\Serializer\Normalizer\DenormalizerInterface:
        alias: 'serializer'

    Symfony\Component\Serializer\Normalizer\NormalizerInterface:
        alias: 'serializer'

    SpotifyWebAPI\Session:
        arguments:
            $clientId: '%env(SPOTIFY_CLIENT_ID)%'
            $clientSecret: '%env(SPOTIFY_CLIENT_SECRET)%'
            $redirectUri: '%env(SPOTIFY_REDIRECT_URI)%'

    SpotifyWebAPI\SpotifyWebAPI:
        arguments:
            $options:
                auto_refresh: true
                auto_retry: true
                return_assoc: true
            $session:
                '@SpotifyWebAPI\Session'
