services:
  database:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./var/lib/database:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
