set shell := ["powershell.exe", "-Command"]

MESSENGER_VERBOSITY := '-v'
PHP := 'php bin/console'
ENV_FILE := '.env.local'

docker_up: docker_build
    docker-compose up -d

docker_down:
    docker-compose down

docker_build:
    docker-compose build

docker_logs:
    docker-compose logs -f

composer_install:
    composer install

composer_update:
    composer update

composer *args='':
    composer {{args}}

messenger_consume: docker_up
    {{PHP}} messenger:consume --all {{MESSENGER_VERBOSITY}}

messenger_consume_dev:
    {{PHP}} messenger:consume --all {{MESSENGER_VERBOSITY}}

messenger_debug:
    {{PHP}} debug:messenger

messenger_stop:
    {{PHP}} messenger:stop-workers

scheduler_debug:
    {{PHP}} debug:scheduler

spotify_tracker_start: messenger_consume

cache_clear:
    {{PHP}} cache:clear

cache_warmup: cache_clear
    {{PHP}} cache:warmup

migration_new:
    {{PHP}} doctrine:migrations:generate

migration_make:
    {{PHP}} make:migration

migration_list:
    {{PHP}} doctrine:migrations:status

migration_apply: docker_up
    {{PHP}} doctrine:migrations:migrate --no-interaction

fixtures options='-c 100':
    {{PHP}} app:fixtures {{options}}

server_start:
    symfony server:start --allow-all-ip

server_stop:
    symfony server:stop

server_logs:
    symfony server:log

spotify_login code:
    docker run \
        --rm \
        --env-file {{ENV_FILE}} \
        -e SPOTIFY_CODE='{{code}}' \
        --network spotifytracker_default \
        --name spotify-login \
        lukamrt/spotify-tracker-scheduler

docker_build_publish:
    docker buildx build --platform linux/arm64 -t lukamrt/spotify-tracker-scheduler --push .

phpstan:
    vendor/bin/phpstan analyse -c phpstan.neon

rector:
    vendor/bin/rector process
