nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']
        allow_headers: ['*']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: false
        forced_allow_origin_value: ~
        skip_same_as_origin: false
    paths:
        '^/api/':
            origin_regex: false
            allow_origin: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']
            allow_headers: ['*']
            max_age: 3600
